# Site
repository: sproogen/resume-theme
favicon: favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cuauhtemoc Ramos
title: Estudiante de ingenieria informatica
email: cuauhtemoc.ramos9328@alumnos.udg.mx
website: www.github.com/cuauhtemoc18

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  cuauhtemoc18
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username:  cuauhtemoc-ramos-210114271
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: channel/UCUrr9dxIHuEyXfHvhQ10dOA
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola mi nombre es Cuauhtemoc Ramos soy estudiante de ingenieria informatica en la universidad de guadalajara y soy apasionado por la ciberseguridad, redes y linux. Me gusta aprender de manera autodidacta
  y hacer cursos y certificaciones para poner a prueba mis habilidades aprendidas.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  #- title: Projects # Title for the section
   # layout: list # Type of content section (list/text)
    #content:
     # - layout: top-middle
      #  title: Super awesome project
       # link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
         # I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tryhackme
        link: https://tryhackme.com/
        # link_text: boringcompany.com
        sub_title: Pentesting
        caption: Enero 2023
        quote: >
          Resolviendo rooms y maquinas
        description: | # this will include new lines to allow paragraphs
            En diversos cursos especialmente en la plataforma tryhackme he tenido experiencia practica al realizar diferentes rooms con tematica de ciberseguridad como puede ser: criptografia, redes, o maquinas donde se pueden poner a prueba las habilidades relacionadas con el pentesting.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara (CUCEI)
        caption: 2020B
        sub_title: Ingenieria informatica
        quote: >
          La Universidad de Guadalajara es una institución heredera de una tradición educativa de más de doscientos años de historia. Actualmente, la Universidad se desarrolla a partir de un modelo de red que se integra por seis centros universitarios temáticos –especializados en un campo disciplinar y con sede en la Zona Metropolitana de Guadalajara–, nueve centros universitarios regionales –con carácter interdisciplinar y establecidos en distintas regiones del Estado–, un Sistema de Educación Media Superior –con 165 planteles distribuidos en todo Jalisco–, así como un Sistema de Universidad Virtual, que ofrece estudios superiores en la modalidad a distancia.
        description: | # this will include new lines to allow paragraphs
          En mi estancia actual como universitario he aprendido muchas habilidades relacionadas con la seguridad como el uso de maquinas virtuales y sistemas operativos basados en linux, redes, programacion, base de datos, etc. Tambien comienzan a ofertar cursos y diplomados dedicados espesificamente con la ciberseguridad que no dudare al tomarlos.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Algunos de mis pasatiempos fuera de mis estudios son:
      - Hacer deporte (futbol, voleibol, gym)
      - Gaming
      - Ver series y peliculas animadas y no animadas
      - Jugar al poker

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
